# Generated by Django 3.0.6 on 2020-05-24 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('subject', models.TextField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, max_length=60)),
            ],
        ),
    ]
