# Generated by Django 3.0.6 on 2020-05-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
    ]
